### ISSUE TITLE
Upgrade and test Gradle config

### ISSUE THREAD

**Issue by murphye** [edeandrea/todo-spring-quarkus#4]
See my latest changes to pom.xml and the application.properties

**Comment by edeandrea** [comment]
@murphye Why the need for the `http.host` and the root path additions to `application.properties`?

**Comment by murphye** [comment]
http.host Spring Boot uses 0.0.0.0 instead of 127.0.0.1 even in dev mode so this makes them equivalent. Was an issue for me using Windows WSL.

root path needed because of changes in Quarkus 1.11 that uses `/q` endpoint by default. I don't really like this change. https://quarkus.io/blog/quarkus-1-11-0-final-released/

**Comment by edeandrea** [comment]
I upgraded the gradle version as well on the `gradle` branch.
